### ISSUE TITLE
failed on last step

### ISSUE THREAD

**Issue by ksIsCute** [crwn1337/wine_injector#3]
i get this error after trying `cmake --build .`
every other step worked completely fine.
```
gmake[2]: x86_64-w64-mingw32-gcc: No such file or directory
gmake[2]: *** [CMakeFiles/wine_injector.dir/build.make:76: CMakeFiles/wine_injector.dir/main.c.o] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/wine_injector.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by ksIsCute** [comment]
fixed, had to install https://www.mingw-w64.org/downloads/

**Comment by ksIsCute** [comment]
`VirtualAllocEx failed.`
![image](https://github.com/crwn1337/wine_injector/assets/92867218/e701f076-7719-4c76-aea9-1b033b902c88)

**Comment by crwn1337** [comment]
Really sorry for not replying, I didn't get any notifications for some reason?

This could be kind of tricky, but try using absolute paths instead of relative paths ex:
```
wine /home/crwn/wine_injector.exe /home/crwn/GDMenu.dll /home/crwn/GeometryDash/GeometryDash.exe
```
(this is just an example, replace them with your actual places)

If that still doesnt work try prefixing the dll and exe with Z: (not the injector)
```
wine /home/crwn/wine_injector.exe Z:/home/crwn/GDMenu.dll Z:/home/crwn/GeometryDash/GeometryDash.exe
```
