### ISSUE TITLE
"CreateProcessA failed." on launch

### ISSUE THREAD

**Issue by heavennborn** [crwn1337/wine_injector#6]
![image](https://github.com/user-attachments/assets/d87c85d4-dcdc-4e38-8bf8-9ea7e07cfde6)
Trying to inject 3dmigoto into zenlezz zone zero..

**Comment by crwn1337** [comment]
`CreateProcessA` failing would usually indicate it cant find the executable, when i wrote this small project, i didnt read about the windows api at all, so there are massive issues that I cant really solve since i dont have wine installed and i dont cheat anymore

you can try running with quotes and using windows paths for the files:
```
wine "wine_injector.exe" "C:/Program Files/PROGS/ZenlessZoneZeroGame/ZenlessZoneZero.exe" "C:/Program Files/PROGS/3Dmigoto-ZZZ-Dev/3dmigoto.dll"
```
(written out by hand so make sure the paths are correct)
